name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
  LATEST_IMAGE_TAG: latest
  PAST_IMAGE_TAG: past

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, tag, and push image to Docker HubK
        id: build-image
        run: |
          docker pull $DOCKER_REPOSITORY:$LATEST_IMAGE_TAG
          docker tag $DOCKER_REPOSITORY:$LATEST_IMAGE_TAG $DOCKER_REPOSITORY:$PAST_IMAGE_TAG
          docker push $DOCKER_REPOSITORY:$PAST_IMAGE_TAG
          docker build -t $DOCKER_REPOSITORY:$LATEST_IMAGE_TAG .
          docker push $DOCKER_REPOSITORY:$LATEST_IMAGE_TAG