name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  ECR_URI: ${{ secrets.ECR_URI }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_EB_APPLICATION_NAME: ${{ secrets.AWS_EB_APPLICATION_NAME }}
  AWS_EB_APPLICATION_ENV_NAME: ${{ secrets.AWS_EB_APPLICATION_ENV_NAME }}
  LATEST_IMAGE_TAG: latest
  PAST_IMAGE_TAG: past

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        run: |
#          docker pull $ECR_URI:$LATEST_IMAGE_TAG
#          docker tag $ECR_URI:$LATEST_IMAGE_TAG $ECR_URI:$PAST_IMAGE_TAG
          docker push $ECR_URI:$PAST_IMAGE_TAG
          docker build -t $ECR_URI:$LATEST_IMAGE_TAG .
          docker push $ECR_URI:$LATEST_IMAGE_TAG

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_APPLICATION_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{steps.current-time.outputs.formattedTime}}
          deployment_package: docker-compose.yml